function T = LQR(q_hat, w_hat, qd, wd, I, L1, L2)
% desired quaternion dot
qd_dot = 0.5*E(qd)*wd;

% control torque
T = skew(w_hat)*I*w_hat + I*((E(qd)'*E(q_hat))^-1)*...
    (-2*(E(qd_dot)')*O(w_hat) ...
    - L2*(E(qd)'*O(w_hat) + 2*E(qd_dot)') ...
    - 2*L1*E(qd)' ...
    + 0.5*E(qd)'*(w_hat'*w_hat))*q_hat;
end